server:
  port: 8080

spring:
  application:
    name: todo-backend
  
  # 数据库配置
  datasource:
    driver-class-name: org.opengauss.Driver
    url: jdbc:opengauss://localhost:5432/todo
    username: todo
    password: todo@123
  
  # JPA 配置
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Jackson 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  # 静态资源配置
  web:
    resources:
      static-locations: classpath:/static/

# JWT 配置
jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-for-jwt-token-generation-and-verification}
  expiration: ${JWT_EXPIRATION:3600}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400}

# 跨域配置
cors:
  allowed-origins: http://localhost:8080
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: Authorization,Content-Type
  allow-credentials: true
  max-age: 3600 

logging:
  level:
    root: INFO
    build.loop.todo: DEBUG
    org.springframework.security: DEBUG 